name: Node.js CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.nvm.outputs.NVMRC }}
    steps:
      - uses: actions/checkout@v2

      - id: setup-node
        name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm i

      - id: persist-node_modules
        name: Persist node_modules
        uses: ./.github/actions/persist-node_modules
  
  changes:
    runs-on: ubuntu-latest
    outputs:
      mocha: ${{ steps.filter.outputs.mocha }}
      nestjs: ${{ steps.filter.outputs.nestjs }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          nestjs:
            - 'recipes/nestjs/**'
          mocha:
            - 'recipes/mocha/**'

  test-default:
    needs: [setup, changes]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: setup-node
        name: Setup Node.js
        uses: ./.github/actions/setup-node

      - id: install-docker-compose
        name: Install docker-compose
        uses: ./.github/actions/install-docker-compose

      - id: restore-node_modules
        name: Restore node_modules
        uses: ./.github/actions/restore-node_modules

      - name: Run Default Tests
        run: npm test

  test-nestjs:
    needs: [setup, changes, test-default]
    if: ${{ needs.changes.outputs.nestjs == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: setup-node
        name: Setup Node.js
        uses: ./.github/actions/setup-node

      - id: install-docker-compose
        name: Install docker-compose
        uses: ./.github/actions/install-docker-compose

      - id: restore-node_modules
        name: Restore node_modules
        uses: ./.github/actions/restore-node_modules

      - name: Run NestJS Tests
        run: npm run test:nestjs

  test-mocha:
    needs: [setup, changes, test-default]
    if: ${{ needs.changes.outputs.mocha == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: setup-node
        name: Setup Node.js
        uses: ./.github/actions/setup-node

      - id: install-docker-compose
        name: Install docker-compose
        uses: ./.github/actions/install-docker-compose

      - id: restore-node_modules
        name: Restore node_modules
        uses: ./.github/actions/restore-node_modules

      - name: Run Mocha Tests
        run: npm run test:mocha
