name: Node.js CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.nvm.outputs.NVMRC }}
    steps:
      - uses: actions/checkout@v2

      - id: setup-node
        name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm i

      - id: persist-node_modules
        name: Persist node_modules
        uses: ./.github/actions/persist-node_modules

  test-default:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: setup-node
        name: Setup Node.js
        uses: ./.github/actions/setup-node

      - id: install-docker-compose
        name: Install docker-compose
        uses: ./.github/actions/install-docker-compose

      - id: restore-node_modules
        name: Restore node_modules
        uses: ./.github/actions/restore-node_modules

      - name: Run Default Tests
        run: npm test

  test-nestjs:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            nestjs:
              - 'recipes/nestjs/**/*'

      - name: Skip if No Changes in NestJS
        if: steps.changes.outputs.nestjs != 'true'
        run: echo "No changes detected in recipes/nestjs. Skipping."

      - id: setup-node
        if: steps.changes.outputs.nestjs == 'true'
        name: Setup Node.js
        uses: ./.github/actions/setup-node

      - id: install-docker-compose
        if: steps.changes.outputs.nestjs == 'true'
        name: Install docker-compose
        uses: ./.github/actions/install-docker-compose

      - id: restore-node_modules
        if: steps.changes.outputs.nestjs == 'true'
        name: Restore node_modules
        uses: ./.github/actions/restore-node_modules

      - name: Run NestJS Tests
        if: steps.changes.outputs.nestjs == 'true'
        run: npm run test:nestjs

  test-mocha:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            mocha:
              - 'recipes/mocha/**/*'  

      - name: Skip if No Changes in Mocha
        if: steps.changes.outputs.tf != 'true'
        run: echo "No changes detected in recipes/mocha. Skipping."

      - id: setup-node
        if: steps.changes.outputs.tf == 'true'
        name: Setup Node.js
        uses: ./.github/actions/setup-node

      - id: install-docker-compose
        if: steps.changes.outputs.tf == 'true'
        name: Install docker-compose
        uses: ./.github/actions/install-docker-compose

      - id: restore-node_modules
        if: steps.changes.outputs.tf == 'true'
        name: Restore node_modules
        uses: ./.github/actions/restore-node_modules

      - name: Run Mocha Tests
        if: steps.changes.outputs.tf == 'true'
        run: npm run test:mocha
